### PR TITLE
Upgrade to Elm 0.19

### PR DESCRIPTION
**Pull request by shuhei**
Changes:

- `elm-package.json` -> `elm.json`
- Updated usages of `Html.Attributes.style`
- `toString` -> `Debug.toString` because its usage is polymorphic
- Removed `Color` package (doesn't exist anymore)
- 4-value tuple -> an explicit `TestCase` type
- Also formatting with `elm-format`

~~Still including `elm-stuff` because it has been [intentionally kept](https://github.com/elmbridge/elm-basics/issues/7).~~ Removing `elm-stuff` because it doesn't help us offline anymore (See the comment below).

### CODE REVIEW

**Comment by avh4** [comment]
I think the argument about keeping `elm-stuff` no longer applies in Elm 0.19, because the downloaded package dependencies are now downloaded to `~/.elm/` instead of to `./elm-stuff/`, and `elm-stuff` in 0.19 only includes things that can be recreated from the source files.  So I think we can remove the folder in this upgrade.

**Comment by avh4** [comment]
In 0.19, the `Color` type moved to https://package.elm-lang.org/packages/avh4/elm-color/latest/, but I also think it's fine to just remove that dependency here.

**Comment by michaelglass** [comment]
thank you!

**Comment by shuhei** [comment]
@avh4 Ah, I didn't know the change of `elm-stuff`'s role. Removed it in a new commit. Thank you!

**Comment by michaelglass** [comment]
can we get this merged?

**Comment by shuhei** [comment]
Thank you for your reviews and merging!

**Pull request merged**
